image:
    convertigo

# these kind of work but don't save some usr folders
#   jenkins/jenkins
#   jenkins/jenkins:lst 
#   node:alpine
#  vgaidarji/docker-android-cordova
    
    
    
#Does not work
 #  jimlei/alpine-nodejs
 #   node/alpine  
 #   jimlei:alpine-nodejs
 #    woahbase/alpine-ionic  
