image:
    woahbase/alpine-ionic


# these kind of work but don't save some usr folders
#   jenkins/jenkins
#   jenkins/jenkins:lst 
#   node:alpine
    
    
    
#Does not work
 #  jimlei/alpine-nodejs
 #   node/alpine  
 #   jimlei:alpine-nodejs
    
